# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
#   kernelspec:
#     display_name: Python (minimal)
#     language: python
#     name: python-minimal
# ---

# %% [markdown]
# # Download scRNA-seq Files from HISE or GEO
# ### By [Aishwarya Chander](aishwarya.chander@alleninstitute.org), Allen Institute for Immunology
#
# **Purpose**: Download all `.h5` files for the longitudinal MM study from HISE
# using file UUIDs in the metadata, then append local file paths back to the
# metadata CSV.
#
# **Inputs**: `scrna_metadata.csv` (generated by `01-make_metadata.R`)
# **Outputs**: Updated `scrna_metadata.csv` with `manual.file_paths` and `manual.batch_id` columns

# %% Imports
import pandas as pd
import numpy as np
import os
import re
import time
import fnmatch
import hisepy as hp

# %% Configuration
metadata_dir = '../../../data/rna/metadata'
if not os.path.exists(metadata_dir):
    os.makedirs(metadata_dir)

input_dir = '../../../data/rna/raw-h5/' # Based on HISE Input dir -- Adjust to where your .h5s live
batch_size = 30

# %% Load metadata
metadata = pd.read_csv(os.path.join(metadata_dir, 'scrna_metadata.csv'))
print(f"Loaded metadata: {metadata.shape[0]} samples")

# %% Download .h5 files in batches
file_ids = list(metadata['file.id'].unique())
batches = [file_ids[i:i + batch_size] for i in range(0, len(file_ids), batch_size)]

print(f"Downloading {len(file_ids)} files in {len(batches)} batches")

for i, batch in enumerate(batches):
    start = time.time()
    hp.cache_files(batch)
    elapsed = time.time() - start
    print(f"Batch {i + 1}/{len(batches)} ({len(batch)} files) — {elapsed:.1f}s")

## Each batch took 40-47s which is a total of 35 minutes for all files.

# %% Add local file paths to metadata
def find_file_paths_with_extension(directory, extension):
    matches = []
    for root, _, filenames in os.walk(directory):
        for filename in fnmatch.filter(filenames, f'*.{extension}'):
            matches.append(os.path.join(root, filename))
    return matches

metadata['manual.extracted_name'] = metadata['file.name'].apply(os.path.basename)

paths_df = pd.DataFrame({'manual.file_paths': find_file_paths_with_extension(input_dir, 'h5')})
paths_df['manual.extracted_name'] = paths_df['manual.file_paths'].apply(os.path.basename)
paths_df['manual.batch_id'] = paths_df['manual.extracted_name'].apply(lambda x: x.split('-')[0])

metadata = metadata.merge(paths_df, on='manual.extracted_name', how='left')
print(f"Final metadata: {metadata.shape[0]} rows, {metadata.shape[1]} columns")

# %% Save
metadata.to_csv(os.path.join(metadata_dir, 'scrna_metadata.csv'), index=False)
print(f"Saved to {metadata_dir}/scrna_metadata.csv")
