#' Identifier Genes for Different Cell Types in ssRNASeq
#'
#' A list of cell type names that map to vectors of genes.
#'
#' @name cell_types_rnaseq
#' @export
cell_types_rnaseq = list(
    'Beffector'= c("FCRL3", "TBX21", "ITGAX", "PDCD1", "ZEB2", "FCRL5"),
    'Bmemory'= c("MS4A1", "HLA-DRA", "PAX5", "AIM2"),
    'Bnaive'= c("MS4A1", "HLA-DRA", "PAX5", "IGHD", "CD44"),
    'Bplasma'= c("PRDM1", "XBP1", "MZB1", "FKBP11", "DNTT", "JCHAIN"),
    'Bprecursor'= c("VPREB1", "VPREB2", "MME", "CD79B"),
    'Btransitional'= c("PAX5", "MME", "IGHM", "IGHD"),
    'Dcasdc'= c("AXL", "CD86", "SIGLEC6", "CLEC4C"),
    'Dcc1'= c("CLEC9A", "XCR1"),
    'Dcc2'= c("ITGAX", "CLEC10A", "FLT3"),
    'Dcp'= c("TCF4", "IRF8", "SERPINF1"),
    'Monocd14'= c("S100A9", "CCR2", "CD14", "FGR", "ITGAX"),
    'Monocd16'= c("FCGR3A", "IRF8", "LY86", "LST1"),
    'Monointermediate'= c("CCR5"),
    'Nkcd56bright'= c("TYROBP", "KLRB1", "KLRF1", "IL7R", "AREG", "SPINK2", "NCAM1", "ILRB2"),
    'Nkcd56intermediate'= c("TYROBP", "KLRB1", "KLRK1", "NKG7", "CST7", "ADGRG1", "GZMB", "CLIC3"),
    'Prog_b'= c("VPREB1", "PAX5", "MME", "IGLL1", "CD79B"),
    'Prog_clp'= c("DNTT", "VPREB1"),
    'Prog_dc'= c("RUNX2", "IRF8", "IL3RA", "STI4"),
    'Prog_early_ery'= c("HES6", "GATA1"),
    'Prog_em'= c("CPA3", "GATA2", "MEIS1"),
    'Prog_hspc'= c("HLF", "ROBO4", "FGD5", "MEIS1"),
    'Prog_late_ery'= c("GATA1", "HBB"),
    'Prog_lmpp'= c("FLT3", "HOXA9", "PROM1", "SELL"),
    'Prog_mk'= c("MEF2C", "PBX1"),
    'Prog_cmp'= c("MPO", "CEBPA", "SPI1", "CEBPD", "CSF3R"),
    'T_cd4_memory'= c("CD4", "KLRB1", "CCR6", "CD82", "CCR7", "KLRG1", "GKMZ", "LTB"),
    'T_cd4_naive'= c("CD4", "CCR7", "SELL", "AIF1"),
    'T_cd8_memory'= c("CD8A", "CCR7", "GNLY", "ADGRG1", "ITGAM", "KLRC3"),
    'T_cd8_naive'= c("CD8A", "CCR7", "SELL", "AIF1"),
    'T_dn'= c("LGALS3"),
    'T_gd'= c("KLRB1", "TRDC", "GZMK", "IL32", "DUSP2", "NKG7"),
    'T_mait'= c("KLRB1"),
    'T_nk_proliferating'= c("MKI67", "KLRD1"),
    'T_regs'= c("FOXP3", "TRAC", "IKZF2", "IL2RA", "FOXP1", "ITGAE", "RTKN2", "CD69")
)


#' Column Specification for FH1 Assembled Labs Dataset
#'
#' This column specification defines the data types for each column in the
#' FH1 Assembled Labs dataset. It is used when reading the dataset from a CSV
#' file to ensure that each column is imported with the correct type, facilitating
#' consistent data handling and analysis.
#' @name FH1AssembledLabsColumnSpec
#' @importFrom readr cols
#' @export
FH1AssembledLabsColumnSpec <- readr::cols(
  Subject = readr::col_factor(),
  Cohort = readr::col_factor(),
  Sex = readr::col_factor(),
  Race = readr::col_factor(),
  Ethnicity = readr::col_factor(),
  BirthYear = readr::col_double(),
  ageAtEnrollment = readr::col_double(),
  visitName = readr::col_factor(),
  visitDetails = readr::col_factor(),
  sampleGuid = readr::col_character(),
  sampleKitGuid = readr::col_character(),
  drawDate = readr::col_date(format = "%Y-%m-%d"),
  daysSinceFirstVisit = readr::col_double(),
  bc.basophil_count = readr::col_double(),
  bc.eosinophil_count = readr::col_double(),
  bc.hematocrit = readr::col_double(),
  bc.hemoglobin = readr::col_double(),
  bc.immature_granulocyte_count = readr::col_double(),
  bc.lymphocyte_count = readr::col_double(),
  bc.mch = readr::col_double(),
  bc.mchc = readr::col_double(),
  bc.mcv = readr::col_double(),
  bc.monocyte_count = readr::col_double(),
  bc.neutrophil_count = readr::col_double(),
  bc.perc_basophils = readr::col_double(),
  bc.perc_eosinophils = readr::col_double(),
  bc.perc_immature_granulocytes = readr::col_double(),
  bc.perc_lymphocytes = readr::col_double(),
  bc.perc_monocytes = readr::col_double(),
  bc.perc_neutrophils = readr::col_double(),
  bc.platelet_count = readr::col_double(),
  bc.rdw = readr::col_double(),
  bc.rdwcv = readr::col_double(),
  bc.red_blood_cell_count = readr::col_double(),
  bc.wbc = readr::col_double(),
  chem.albumin = readr::col_double(),
  chem.alkaline_phosphatase = readr::col_double(),
  chem.alt = readr::col_double(),
  chem.anion_gap = readr::col_double(),
  chem.ast = readr::col_double(),
  chem.bun = readr::col_double(),
  chem.calcium = readr::col_double(),
  chem.cl = readr::col_double(),
  chem.co2 = readr::col_double(),
  chem.creatinine = readr::col_double(),
  chem.egfr_aa = readr::col_double(),
  chem.egfr_non_aa = readr::col_double(),
  chem.glucose = readr::col_double(),
  chem.ldh = readr::col_double(),
  chem.magnesium = readr::col_double(),
  chem.phosphate = readr::col_double(),
  chem.potassium = readr::col_double(),
  chem.protein = readr::col_double(),
  chem.sodium = readr::col_double(),
  chem.t_bili = readr::col_double(),
  cmv.ab_screen_index_value = readr::col_double(),
  cmv.ab_screen_result = readr::col_factor(),
  cyto.17p_loss = readr::col_factor(),
  cyto.1p_gain = readr::col_factor(),
  cyto.1p_loss = readr::col_factor(),
  cyto.high_risk = readr::col_factor(),
  cyto.karyotype = readr::col_factor(),
  cyto.t11_14 = readr::col_factor(),
  cyto.t14_16 = readr::col_factor(),
  cyto.t14_20 = readr::col_factor(),
  cyto.t4_14 = readr::col_factor(),
  igg.iga = readr::col_double(),
  igg.igg = readr::col_double(),
  igg.igm = readr::col_double(),
  igg.immunofixation = readr::col_factor(),
  igg.k_flc = readr::col_double(),
  igg.kl_flc_ratio = readr::col_double(),
  igg.l_flc = readr::col_double(),
  igg.mono_1_id = readr::col_factor(),
  igg.mono_1_quant = readr::col_double(),
  infl.esr = readr::col_double(),
  infl.hs_crp = readr::col_double(),
  lip.cholesterol_hdl_ratio = readr::col_double(),
  lip.cholesterol_hdl = readr::col_double(),
  lip.cholesterol_ldl = readr::col_double(),
  lip.cholesterol_non_hdl = readr::col_double(),
  lip.cholesterol_total = readr::col_double(),
  lip.triglycerides = readr::col_double(),
  spe.albumin = readr::col_double(),
  spe.alpha1 = readr::col_double(),
  spe.alpha2 = readr::col_double(),
  spe.b2m = readr::col_double(),
  spe.beta = readr::col_double(),
  spe.gamma = readr::col_double(),
  spe.protein = readr::col_double(),
  tb.end_induction_response = readr::col_factor(),
  tb.perc_abnormal_flow = readr::col_double(),
  tb.perc_abnormal_morph = readr::col_double(),
  tb.was_perc_abnormal_by_ihc = readr::col_factor()
)

DataBMColumnSpec <- readr::cols(
  SampleID = readr::col_factor(),
  Index = readr::col_factor(),
  OlinkID = readr::col_character(),
  UniProt = readr::col_character(),
  Assay = readr::col_character(),
  MissingFreq = readr::col_double(),
  Panel = readr::col_factor(),
  Panel_Lot_Nr = readr::col_factor(),
  PlateID = readr::col_factor(),
  QC_Warning = readr::col_factor(),
  LOD = readr::col_double(),
  NPX = readr::col_double(),
  Normalization = readr::col_factor(),
  Assay_Warning = readr::col_factor(),
  is_technical_control = readr::col_logical(),
  SampleType = readr::col_factor(),
  Subject = readr::col_factor(),
  Sex = readr::col_factor(),
  Age = readr::col_double(),
  Race = readr::col_factor(),
  Cohort = readr::col_factor(),
  Visit = readr::col_factor(),
  CollectionDate = readr::col_date(format = "%Y-%m-%d"),
  sampleKitGuid = readr::col_character(),
  is_normal_BM = readr::col_logical(),
  is_MM_sample = readr::col_logical(),
  AssayUnique = readr::col_factor()
)

DataPlasmaColumnSpec <- readr::cols(
  SampleID = readr::col_character(),
  Index = readr::col_double(),
  AssayUnique = readr::col_character(),
  OlinkID = readr::col_character(),
  UniProt = readr::col_character(),
  Assay = readr::col_character(),
  MissingFreq = readr::col_double(),
  Panel = readr::col_character(),
  Panel_Lot_Nr = readr::col_factor(),
  PlateID = readr::col_factor(),
  Normalization = readr::col_character(),
  Assay_Warning = readr::col_character(),
  sampleKitGuid = readr::col_character(),
  UniqueAssay = readr::col_character(),
  N_Bridge = readr::col_factor(),
  BatchOffset = readr::col_double(),
  NPX = readr::col_double(),
  LOD = readr::col_double(),
  sampleWarningBridge = readr::col_character(),
  BridgingDetails = readr::col_character(),
  filename = readr::col_character(),
  BatchID = readr::col_factor(),
  is_bridgingControl = readr::col_double(),
  visitName = readr::col_factor(),
  visitDetails = readr::col_factor(),
  drawDate = readr::col_datetime(format = "%Y-%m-%d"),
  daysSinceFirstVisit = readr::col_double(),
  diseaseStatesRecordedAtVisit = readr::col_factor(),
  file.fileType = readr::col_character(),
  Sex = readr::col_factor(),
  birthYear = readr::col_double(),
  Ethnicity = readr::col_factor(),
  Race = readr::col_factor(),
  Subject = readr::col_factor(),
  Cohort = readr::col_factor(),
  sampleWarningBride = readr::col_factor()
)
